2016/10/09 11:20:08 [emerg] 65244#0: bind() to 0.0.0.0:8080 failed (48: Address already in use)
2016/10/09 11:20:08 [emerg] 65244#0: bind() to 0.0.0.0:8080 failed (48: Address already in use)
2016/10/09 11:20:08 [emerg] 65244#0: bind() to 0.0.0.0:8080 failed (48: Address already in use)
2016/10/09 11:20:08 [emerg] 65244#0: bind() to 0.0.0.0:8080 failed (48: Address already in use)
2016/10/09 11:20:08 [emerg] 65244#0: bind() to 0.0.0.0:8080 failed (48: Address already in use)
2016/10/09 11:20:08 [emerg] 65244#0: still could not bind()
2016/10/14 11:27:28 [error] 13505#0: *2 failed to load inlined Lua code: header_filter_by_lua:2: '=' expected near '-', client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2016/10/14 20:35:06 [emerg] 13484#0: directive "content_by_lua_file" is not terminated by ";" in /Users/lintide/github/helloOpenresty/conf/nginx.conf:13
2016/10/14 21:45:28 [emerg] 13484#0: "lua_package_path" directive is not allowed here in /Users/lintide/github/helloOpenresty/conf/nginx.conf:1
2016/10/14 21:46:04 [emerg] 13484#0: "lua_package_path" directive is not allowed here in /Users/lintide/github/helloOpenresty/conf/nginx.conf:1
2016/10/14 21:46:33 [emerg] 13484#0: "lua_package_path" directive is not allowed here in /Users/lintide/github/helloOpenresty/conf/nginx.conf:1
2016/10/14 21:46:49 [emerg] 13484#0: "lua_package_path" directive is not allowed here in /Users/lintide/github/helloOpenresty/conf/nginx.conf:1
2016/10/14 21:49:39 [emerg] 13484#0: "lua_package_path" directive is not allowed here in /Users/lintide/github/helloOpenresty/conf/nginx.conf:1
2016/10/14 21:51:36 [emerg] 13484#0: unexpected "}" in /Users/lintide/github/helloOpenresty/conf/nginx.conf:16
2016/10/14 21:52:12 [emerg] 13484#0: unexpected "}" in /Users/lintide/github/helloOpenresty/conf/nginx.conf:16
2016/10/14 21:53:00 [emerg] 13484#0: unexpected "}" in /Users/lintide/github/helloOpenresty/conf/nginx.conf:16
2016/10/14 21:53:34 [emerg] 13484#0: directive "content_by_lua_file" is not terminated by ";" in /Users/lintide/github/helloOpenresty/conf/nginx.conf:20
2016/10/14 21:55:03 [error] 14483#0: *11 failed to load external Lua file "/app/httpc.lua": cannot open /app/httpc.lua: No such file or directory, client: 127.0.0.1, server: , request: "GET /httpc HTTP/1.1", host: "localhost:8080"
2016/10/14 21:55:37 [error] 14483#0: *12 failed to load external Lua file "/app/index.lua": cannot open /app/index.lua: No such file or directory, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2016/10/14 21:57:06 [error] 14483#0: *13 failed to load external Lua file "/app/index.lua": cannot open /app/index.lua: No such file or directory, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2016/10/14 22:05:52 [error] 14535#0: *18 lua entry thread aborted: runtime error: /Users/lintide/github/helloOpenresty/app/httpc.lua:1: module 'resty.http' not found:
	no field package.preload['resty.http']
	no file '/libs/lua-resty-http/lib/resty/http.lua'
	no file '/usr/local/Cellar/openresty/1.11.2.1/site/lualib/resty/http.lua'
	no file '/usr/local/Cellar/openresty/1.11.2.1/site/lualib/resty/http/init.lua'
	no file '/usr/local/Cellar/openresty/1.11.2.1/lualib/resty/http.lua'
	no file '/usr/local/Cellar/openresty/1.11.2.1/lualib/resty/http/init.lua'
	no file './resty/http.lua'
	no file '/usr/local/Cellar/openresty/1.11.2.1/luajit/share/luajit-2.1.0-beta2/resty/http.lua'
	no file '/usr/local/share/lua/5.1/resty/http.lua'
	no file '/usr/local/share/lua/5.1/resty/http/init.lua'
	no file '/usr/local/Cellar/openresty/1.11.2.1/luajit/share/lua/5.1/resty/http.lua'
	no file '/usr/local/Cellar/openresty/1.11.2.1/luajit/share/lua/5.1/resty/http/init.lua'
	no file '/usr/local/Cellar/openresty/1.11.2.1/site/lualib/resty/http.so'
	no file '/usr/local/Cellar/openresty/1.11.2.1/lualib/resty/http.so'
	no file './resty/http.so'
	no file '/usr/local/lib/lua/5.1/resty/http.so'
	no file '/usr/local/Cellar/openresty/1.11.2.1/luajit/lib/lua/5.1/resty/http.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/Cellar/openresty/1.11.2.1/site/lualib/resty.so'
	no file '/usr/local/Cellar/openresty/1.11.2.1/lualib/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/Cellar/openresty/1.11.2.1/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/Users/lintide/github/helloOpenresty/app/httpc.lua:1: in function </Users/lintide/github/helloOpenresty/app/httpc.lua:1>, client: 127.0.0.1, server: , request: "GET /httpc HTTP/1.1", host: "localhost:8080"
2016/10/14 22:06:41 [error] 14540#0: *19 lua entry thread aborted: runtime error: /Users/lintide/github/helloOpenresty/app/httpc.lua:11: attempt to index local 'res' (a nil value)
stack traceback:
coroutine 0:
	/Users/lintide/github/helloOpenresty/app/httpc.lua: in function </Users/lintide/github/helloOpenresty/app/httpc.lua:1>, client: 127.0.0.1, server: , request: "GET /httpc HTTP/1.1", host: "localhost:8080"
2016/10/15 09:43:04 [error] 14661#0: *1 lua entry thread aborted: runtime error: /Users/lintide/github/helloOpenresty/app/httpc.lua:11: attempt to index local 'res' (a nil value)
stack traceback:
coroutine 0:
	/Users/lintide/github/helloOpenresty/app/httpc.lua: in function </Users/lintide/github/helloOpenresty/app/httpc.lua:1>, client: 127.0.0.1, server: , request: "GET /httpc HTTP/1.1", host: "localhost:8080"
2016/10/15 09:46:46 [error] 14681#0: *5 lua entry thread aborted: runtime error: /Users/lintide/github/helloOpenresty/app/httpc.lua:12: attempt to index local 'res' (a nil value)
stack traceback:
coroutine 0:
	/Users/lintide/github/helloOpenresty/app/httpc.lua: in function </Users/lintide/github/helloOpenresty/app/httpc.lua:1>, client: 127.0.0.1, server: , request: "GET /httpc HTTP/1.1", host: "localhost:8080"
2016/10/15 09:48:19 [error] 14681#0: *6 lua entry thread aborted: runtime error: /Users/lintide/github/helloOpenresty/app/httpc.lua:12: attempt to index local 'res' (a nil value)
stack traceback:
coroutine 0:
	/Users/lintide/github/helloOpenresty/app/httpc.lua: in function </Users/lintide/github/helloOpenresty/app/httpc.lua:1>, client: 127.0.0.1, server: , request: "GET /httpc HTTP/1.1", host: "localhost:8080"
2016/10/15 09:48:26 [error] 14693#0: *7 lua entry thread aborted: runtime error: /Users/lintide/github/helloOpenresty/app/httpc.lua:12: attempt to index local 'res' (a nil value)
stack traceback:
coroutine 0:
	/Users/lintide/github/helloOpenresty/app/httpc.lua: in function </Users/lintide/github/helloOpenresty/app/httpc.lua:1>, client: 127.0.0.1, server: , request: "GET /httpc HTTP/1.1", host: "localhost:8080"
2016/10/15 09:53:06 [emerg] 14660#0: directive "resolver" is not terminated by ";" in /Users/lintide/github/helloOpenresty/conf/nginx.conf:16
2016/10/15 09:53:47 [error] 14722#0: *10 lua entry thread aborted: runtime error: /Users/lintide/github/helloOpenresty/app/httpc.lua:17: bad argument #1 to 'log' (bad log level: 200)
stack traceback:
coroutine 0:
	[C]: in function 'log'
	/Users/lintide/github/helloOpenresty/app/httpc.lua:17: in function </Users/lintide/github/helloOpenresty/app/httpc.lua:1>, client: 127.0.0.1, server: , request: "GET /httpc HTTP/1.1", host: "localhost:8080"
2016/10/15 10:23:24 [error] 14726#0: send() failed (61: Connection refused) while resolving, resolver: 114.114.114.114:53
